"""Geometry of categorical predictive distributions."""

from .benchmark import (
    CONNECTIONS,
    CompositionResult,
    evaluate_composition,
    evaluate_quadrilateral,
    jensen_shannon_divergence,
    kl_divergence,
    predict_composition,
)

from .simplex import (
    FISHER_RADIUS,
    analogy,
    bhattacharyya_coefficient,
    exponential_exp,
    exponential_log,
    exponential_parallel_transport,
    fisher_distance,
    fisher_exp,
    fisher_inner,
    fisher_log,
    fisher_parallel_transport,
    mixture_exp,
    mixture_log,
    mixture_parallel_transport,
    sqrt_embed,
    triangle_holonomy_angle,
)
from .softmax import (
    SoftmaxCurvature,
    SoftmaxHessianGeometry,
    centered_unembedding,
    softmax_cubic_contraction,
    softmax_fisher_metric,
    softmax_sectional_curvature,
)
from .field import (
    SemanticConnectionFit,
    alpha_parallel_transport,
    first_order_alpha_transport,
    fit_semantic_alpha,
    local_transport_defect_scalar,
    softmax_probabilities,
)

__all__ = [
    "CONNECTIONS",
    "CompositionResult",
    "FISHER_RADIUS",
    "analogy",
    "bhattacharyya_coefficient",
    "exponential_exp",
    "exponential_log",
    "exponential_parallel_transport",
    "fisher_distance",
    "fisher_exp",
    "fisher_inner",
    "fisher_log",
    "fisher_parallel_transport",
    "mixture_exp",
    "mixture_log",
    "mixture_parallel_transport",
    "sqrt_embed",
    "triangle_holonomy_angle",
    "evaluate_composition",
    "evaluate_quadrilateral",
    "jensen_shannon_divergence",
    "kl_divergence",
    "predict_composition",
    "SoftmaxCurvature",
    "SoftmaxHessianGeometry",
    "centered_unembedding",
    "softmax_cubic_contraction",
    "softmax_fisher_metric",
    "softmax_sectional_curvature",
    "SemanticConnectionFit",
    "alpha_parallel_transport",
    "first_order_alpha_transport",
    "fit_semantic_alpha",
    "local_transport_defect_scalar",
    "softmax_probabilities",
]
